substitutions:
  name: esphome-web-ddb5e8
  friendly_name: LCDWiki 2.8inch ESP32-S3

  imagewidth:  "240"
  imageheight: "320"

  screenwidth:  "240"
  screenheight: "320"
  rotate_display: "0"

  startup_sound: "Home_Connected"
  clock_background_image: "chip"
  imagemodel: "Gwen"

  imagepath: "https://github.com/RealDeco/xiaozhi-esphome/raw/main/images"

  sensor1_entity: "binary_sensor.8266_presense_2_presence"
  light1_entity: "light.livingroom_all_lights"
  sensor1_label: "Tech Room"

  sensor2_entity: "binary_sensor.esp32s3_1_presence"
  light2_entity: "group.kitchen_lights"
  sensor2_label: "Kitchen"

  sensor3_entity: "binary_sensor.esphome_web_1911bf_presence"
  light3_entity: "light.mom_s_room"
  sensor3_label: "Living Room"

  sensor4_entity: "binary_sensor.notifier_2_presence"
  light4_entity: "light.hue_toilet_light_light"
  sensor4_label: "Toilet"

  sensor5_entity: "binary_sensor.8266_presense_presence"
  light5_entity: "switch.nedis_smart_plug_tasmota1"
  sensor5_label: "Hall"

  weather_entity: "weather.forecast_home"

  font_glyphsets: "GF_Latin_Core"
  font_family: Figtree

esp32:
  variant: esp32s3
  flash_size: 16MB
  cpu_frequency: 240MHz
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"

psram:
  mode: octal
  speed: 80MHz

logger:
  level: DEBUG

packages:
  core: !include devices/Under_Development/Modular/core.yaml
  hw:   !include devices/Under_Development/Modular/HW/LCDWiki-2.8_hw.yaml

voice_assistant:
  volume_multiplier: 4.0

micro_wake_word:
  id: mww
  models:
    - model: okay_nabu
      probability_cutoff: 0.85
      sliding_window_size: 5
    - model: hey_jarvis
      probability_cutoff: 0.85
      sliding_window_size: 5
