substitutions:
  name: esphome-web-lcdwiki28
  friendly_name: LCDWiki 2.8inch ESP32-S3

## Modular version Main v1.08

## SETTINGS ######################################################################################################################################

  imagewidth:  "240"
  imageheight: "320"

  screenwidth:  "240"
  screenheight: "320"
  rotate_display: "0"

  startup_sound: "Home_Connected" # (options are: available, Home_Connected, Home_Connected_Male, Computer_Ready)
  clock_background_image: "chip" # (options are: clock, hacker, ha-girl, mission, starrysky, waves, tron)
  imagemodel: "Gwen" # options are:

# Alita, Alfred, Astrobot, Buzz, Casita, Cybergirl, Dory, EVE, Eyes, Eyes2, GLaDOS, Girl1, Guy1, Guy2, Gwen, HA-character, ha-girl, Hacker, Harley,
# Jarvis, Luffy, Mario, Max, Prime, Robochibi, Robocop, Robot, Robotgirl, Sarah, Shaun

# USE ONLINE OR LOCAL MODEL AND WALLPAPER IMAGES, IMAGES SHOULD BE PLACED IN: homeassistant/www/images/
  imagepath: "https://github.com/RealDeco/xiaozhi-esphome/raw/main/images"
#  imagepath: "http://homeassistant.local:8123/local/images/"

## PRESENCE / MOTION SENSORS ########## IF NOT USING THESE LEAVE THEM ALONE, SCRIPT WILL BREAK WITHOUT ###########################################

  sensor1_entity: "binary_sensor.8266_presense_2_presence"
  light1_entity: "light.livingroom_all_lights"
  sensor1_label: "Tech Room"

  sensor2_entity: "binary_sensor.esp32s3_1_presence"
  light2_entity: "group.kitchen_lights"
  sensor2_label: "Kitchen"

  sensor3_entity: "binary_sensor.esphome_web_1911bf_presence"
  light3_entity: "light.mom_s_room"
  sensor3_label: "Living Room"

  sensor4_entity: "binary_sensor.notifier_2_presence"
  light4_entity: "light.hue_toilet_light_light"
  sensor4_label: "Toilet"

  sensor5_entity: "binary_sensor.8266_presense_presence"
  light5_entity: "switch.nedis_smart_plug_tasmota1"
  sensor5_label: "Hall"

  weather_entity: "weather.forecast_home"

##################################################################################################################################################

  font_glyphsets: "GF_Latin_Core"
  font_family: Figtree

esp32:
  variant: esp32s3
  flash_size: 16MB
  cpu_frequency: 240MHz
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"

psram:
  mode: octal
  speed: 80MHz

### USE MODULES FROM GITHUB (default) ############################################################################################################

packages:
  core:
    url: https://github.com/timelf123/xiaozhi-esphome.git
    ref: main
    refresh: 0s
    files:
      - devices/Under_Development/Modular/core.yaml
  hw:
    url: https://github.com/timelf123/xiaozhi-esphome.git
    ref: main
    refresh: 0s
    files:
      - devices/Under_Development/Modular/HW/LCDWiki-2.8_hw.yaml

### USE LOCAL MODULES (read description https://github.com/RealDeco/xiaozhi-esphome/blob/main/devices/Under_Development/Modular/README.md) #######

#packages: # Local
#  core: !include localtest/core.yaml
#  hw:   !include localtest/HW/LCDWiki-2.8_hw.yaml

## ENABLE / DISABLE WAKE WORDS ## IF LOW ON MEMORY, USE LESS WAKE WORDS ##########################################################################

micro_wake_word:
  id: mww
  models:
    - okay_nabu
    - hey_jarvis
#    - alexa
#    - hey_mycroft
#    - model: https://raw.githubusercontent.com/RealDeco/xiaozhi-esphome/refs/heads/main/MicroWakeWords/models/v2/hey_sarah.json
#    - model: https://raw.githubusercontent.com/JohnnyPrimus/Custom_V2_MicroWakeWords/refs/heads/main/models/computer/computer.json
#    - model: https://raw.githubusercontent.com/JohnnyPrimus/Custom_V2_MicroWakeWords/refs/heads/main/models/hey_friday/hey_friday.json
#    - model: https://github.com/kahrendt/microWakeWord/releases/download/okay_nabu_20241226.3/okay_nabu.json
#    - model: https://raw.githubusercontent.com/formatBCE/Respeaker-Lite-ESPHome-integration/refs/heads/main/microwakeword/models/v2/kenobi.json
#    - model: https://raw.githubusercontent.com/esphome/micro-wake-word-models/refs/heads/main/models/v2/experiments/choo_choo_homie.json
#    - model: https://raw.githubusercontent.com/esphome/micro-wake-word-models/refs/heads/main/models/v2/experiments/hey_home_assistant.json
#    - model: https://raw.githubusercontent.com/esphome/micro-wake-word-models/refs/heads/main/models/v2/experiments/hey_peppa_pig.json
#    - model: https://raw.githubusercontent.com/esphome/micro-wake-word-models/refs/heads/main/models/v2/experiments/okay_computer.json

##################################################################################################################################################
